{% set name = "pkginfo" %}
{% set version = "1.5.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c521b92d4bf9a449b59e6b6319b28a866d2be7bc52b2e5288bb0f9a2520ff7ff" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  entry_points:
    - pkginfo = pkginfo.commandline:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pkginfo
    - pkginfo.tests
  commands:
    - pkginfo --help

about:
  home: https://code.launchpad.net/~tseaver/pkginfo/trunk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Query metadatdata from sdists / bdists / installed packages.
  description: |
    This package provides an API for querying the distutils metadata written in
    the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or
    a binary distribution (e.g., created by running ``bdist_egg``)
  doc_url: http://pythonhosted.org/pkginfo/
  dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk

extra:
  recipe-maintainers:
    - jakirkham
    - jankatins
    - mingwandroid
