{% set name = "pkginfo" %}
{% set version = "1.12.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/p/pkginfo/pkginfo-{{ version }}.tar.gz
  sha256: 8ad91a0445a036782b9366ef8b8c2c50291f83a553478ba8580c73d3215700cf

build:
  number: 0
  skip: True  # [py<38]
  entry_points:
    - pkginfo = pkginfo.commandline:main
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pkginfo
    - pkginfo.tests
  commands:
    - pip check
    - pkginfo --help
  requires:
    - pip

about:
  home: https://code.launchpad.net/~tseaver/pkginfo/trunk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Query metadatdata from sdists / bdists / installed packages.
  description: |
    This package provides an API for querying the distutils metadata written in
    the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or
    a binary distribution (e.g., created by running ``bdist_egg``)
  doc_url: https://pythonhosted.org/pkginfo/
  dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk

extra:
  recipe-maintainers:
    - jakirkham
    - jankatins
    - mingwandroid
