{% set name = "pkginfo" %}
{% set version = "1.7.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e7432f81d08adec7297633191bbf0bd47faf13cd8724c3a13250e51d542635bd" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - pkginfo = pkginfo.commandline:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pkginfo
    - pkginfo.tests
  commands:
    - pkginfo --help

about:
  home: https://code.launchpad.net/~tseaver/pkginfo/trunk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Query metadatdata from sdists / bdists / installed packages.
  description: |
    This package provides an API for querying the distutils metadata written in
    the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or
    a binary distribution (e.g., created by running ``bdist_egg``)
  doc_url: http://pythonhosted.org/pkginfo/
  dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk

extra:
  recipe-maintainers:
    - jakirkham
    - jankatins
    - mingwandroid
