{% set version = "1.7.1" %}

package:
  name: pkginfo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pkginfo/pkginfo-{{ version }}.tar.gz
  sha256: e7432f81d08adec7297633191bbf0bd47faf13cd8724c3a13250e51d542635bd

build:
  noarch: python
  number: 0
  entry_points:
    - pkginfo = pkginfo.commandline:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pkginfo
    - pkginfo.tests
  commands:
    - pkginfo --help

about:
  home: https://code.launchpad.net/~tseaver/pkginfo/trunk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Query metadatdata from sdists / bdists / installed packages.
  description: |
    This package provides an API for querying the distutils metadata written in
    the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or
    a binary distribution (e.g., created by running ``bdist_egg``)
  doc_url: http://pythonhosted.org/pkginfo/
  dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk

extra:
  recipe-maintainers:
    - jakirkham
    - jankatins
    - mingwandroid
