{% set name = "pkginfo" %}
{% set version = "1.8.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e7432f81d08adec7297633191bbf0bd47faf13cd8724c3a13250e51d542635bd" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/p/pkginfo/pkginfo-{{ version }}.tar.gz
  sha256: a84da4318dd86f870a9447a8c98340aa06216bfc6f2b7bdc4b8766984ae1867c

build:
  number: 0
  skip: True  # [py<36]
  entry_points:
    - pkginfo = pkginfo.commandline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pkginfo
    - pkginfo.tests
  commands:
    - pip check
    - pkginfo --help
  requires:
    - pip

about:
  home: https://code.launchpad.net/~tseaver/pkginfo/trunk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Query metadatdata from sdists / bdists / installed packages.
  description: |
    This package provides an API for querying the distutils metadata written in
    the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or
    a binary distribution (e.g., created by running ``bdist_egg``)
  doc_url: https://pythonhosted.org/pkginfo/
  dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk

extra:
  recipe-maintainers:
    - jakirkham
    - jankatins
    - mingwandroid
