travis:
  secure:
    BINSTAR_TOKEN: LdjmKmD22yMaoBWiL+oP0+UtIiQ9H6Qsx7yAbh5GTGx12ckR5NGghycZu6izzbYNnLKNcefxfW0la8O8ZYx/ZbgedLc3h0VW2SPP353+5azpOGTm0WL/zEk4aakDBhfr/iWS9XiGTIM5hjlIMhR9SRkkB/O0u9FnexZ7VtRxWFFKCluue4K0qaJtxgPKeM9Z254XLgOuXPL0CPewVBJ1jm96P9wWDVIgcxuGPbw3q2STz7FzgclY4QI4ceI3NMfQMOPqjl7+DH5PGAsTX4YhD/bS5ktSoj4VtaZ+Y3Inrau/18I9rFPc09LesXrciBkNlTRAzUZHLWQf9flQsIthKpInAZdmJKVmiX9UswY6lVal0zrdfFrEJ7ORK3g6L1EoEidzaPpHx9ilydwBYGUCXv/mnQTq1/x+Gx9xw4yYHeAiusxNvky/G1liUBcDo6Hzt60KxTBaudH1W7se5Uo6xLCsrYR4wHWXLpxm745TukidqXUJngbFKkJLsfeuML7X/77BlURYmpH05P+sTKHnABPVVan2aTOtsMWjVx9Vxmsw5wQ6bCdfNrSrb4w4NDuwufUghSnNesZbwC3T6YmpeWIzyBTGzT8g5F56ZZeRUs4LgcnvEaluYjdhl2IhjdltoCHATCaXsCGofHit1aE9L79gm68XagOOSwtWEN9I1mY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
