travis:
  secure:
    BINSTAR_TOKEN: LTsKn9a1ByUOWAeqtberrv1GYu5zYGAHKaOS4KtninmxZizZDR8phMtJYjxX6zxVV5k9C1veJ2LUuZPVOZQWD7WPNfvt/6rf3pdns7fPMQCBaSgvtxjaZwGE5emhLtbnUOXGceRPB5JKN3VcIEB5YA3tw7/eEpGX9CjhNmXLT6qp57oZmgpmwUMbmcMhTkSWC05TcOr9xrZalXPZxk1JCoDtDYCWg9NVvF/Cer7tjAyxeEo3DwQvMvYkzSx8XtAF76iofNzYqDsHTl5Sa49+5avPd7y5Fmc/UXdT54gR+JnHPy44pZdmxPwPSj7429YPFCKLuKDjD3vH6EUA+c7jgInmbxaMiT4jnUK594ZQx2x3VcnIdEurLUVrikBJk9ch7gfIhSap34CO+q3+vJ8e7s0FwGE+mVIyZmcMVLMhxX5wKvxl0VaCJhNA9g3WVGrs//YDQu5fHy37Fb+ehRfDJWtMds963OJBjGy8tQ8SyhRkNBa7LmqVuBaHKRyPFGHmvsczCi9Y24gVOJOtY7Z1cgYHCVKQXA2dVP+iWKs+1ks+e5lsIpHEvWNFxVojqE2MMNWyT3VTapUKOPZZW6DrogFXnbXd5nwh6ZRJK39mhJwMxDPIGjz92+Y0kZeDBUZzS4cqDgeXvc6tSCSK6aX7445hFk+CRA4kdwDObksn8iQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
